///**
// * File generated by Magnet rest2mobile 1.1 - Jun 3, 2016 5:38:20 PM
// * @see {@link http://developer.magnet.com}
// */
//
//package com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api.test;
//
//import android.test.InstrumentationTestCase;
//import android.test.suitebuilder.annotation.SmallTest;
//import android.test.suitebuilder.annotation.Suppress;
//
//import com.magnet.android.mms.MagnetMobileClient;
//import com.magnet.android.mms.async.Call;
//import com.magnet.android.mms.exception.SchemaException;
//import java.util.concurrent.ExecutionException;
//
//import com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api.FactoryAPI;
//import com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api.FactoryAPIFactory;
//
///**
//* This is generated stub to test {@link FactoryAPI}
//* <p>
//* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
//* <ul>
//* <li>Set proper value for the parameters
//* <li>Remove out the @Suppress annotation
//* <li>(optional)Add more asserts for the result
//* <ul><p>
//*/
//
//public class FactoryAPITest extends InstrumentationTestCase {
//  private FactoryAPI factoryAPI;
//
//  @Override
//  protected void setUp() throws Exception {
//    super.setUp();
//
//    // Instantiate a controller
//    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
//    FactoryAPIFactory controllerFactory = new FactoryAPIFactory(magnetClient);
//    factoryAPI = controllerFactory.obtainInstance();
//
//    assertNotNull(factoryAPI);
//  }
//
//  /**
//    * Generated unit test for {@link FactoryAPI#get_Parking_Reservation}
// */
// @Suppress //FIXME : set proper parameter value and un-suppress this test case
// @SmallTest
// public void testGet_Parking_Reservation() throws SchemaException, ExecutionException, InterruptedException {
//   Call<Void> callObject = factoryAPI.get_Parking_Reservation(null);
//   assertNotNull(callObject);
//
//   Void result = callObject.get();
//
//   //TODO : add more asserts
// }
//
//}
