/**
 * File generated by Magnet rest2mobile 1.1 - Jun 3, 2016 5:38:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;


public class FactoryAPIFactory extends ControllerFactory<FactoryAPI> {
  public FactoryAPIFactory(MagnetMobileClient magnetClient) {
    super(FactoryAPI.class, FactoryAPISchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller FactoryAPI
  public static class FactoryAPISchemaFactory extends AbstractControllerSchemaFactory {
    private static FactoryAPISchemaFactory __instance;

    public static synchronized FactoryAPISchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new FactoryAPISchemaFactory();
      }

      return __instance;
    }

    private FactoryAPISchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method get_Parking_Reservation
      JMethod method1 = addMethod("get_Parking_Reservation",
        "allocations",
        "GET",
        void.class,
        null,
        null,
        null);
      method1.setBaseUrl("https://polar-plains-14145.herokuapp.com");
    }

  }

}
