/**
 * File generated by Magnet rest2mobile 1.1 - May 28, 2016 12:00:19 AM
 * @see {@link http://developer.magnet.com}
 */

package com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api;

import com.compscitutorials.basigarcia.navigationdrawervideotutorial.Parking_models.Parking_builder;
import com.compscitutorials.basigarcia.navigationdrawervideotutorial.Parking_models.Users;
import com.compscitutorials.basigarcia.navigationdrawervideotutorial.model.beans.UsersResult;
import com.compscitutorials.basigarcia.navigationdrawervideotutorial.model.beans._ParkingsResult;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import java.util.List;

public interface FactoryAPI_Retrofit {

  Call<List<Users>> getUsers(StateChangedListener listener);
  Call<List<Parking_builder>> get_Parkings(StateChangedListener listener);

}
