/**
 * File generated by Magnet rest2mobile 1.1 - May 28, 2016 12:00:19 AM
 *
 * @see {@link http://developer.magnet.com}
 */
package pl.parking.model;

import com.google.gson.annotations.SerializedName;

/**
 * Generated from json example { "ID" : 1, "password" : "123456", "Login" : "kowal", "Imie" :
 * "robin", "email" : "robin@wp.pl", "Nazwisko" : "robert" }
 */
public class UsersResult {

    private String email;

    @SerializedName("ID")
    private Integer iD;

    @SerializedName("Imie")
    private String imie;

    @SerializedName("Login")
    private String login;

    @SerializedName("Nazwisko")
    private String nazwisko;

    private String password;

    public String getEmail() {
        return email;
    }

    public Integer getID() {
        return iD;
    }

    public String getImie() {
        return imie;
    }

    public String getLogin() {
        return login;
    }

    public String getNazwisko() {
        return nazwisko;
    }

    public String getPassword() {
        return password;
    }

    public static class UsersResultBuilder {
        private UsersResult toBuild = new UsersResult();

        public UsersResultBuilder() {}

        public UsersResult build() {
            return toBuild;
        }

        public UsersResultBuilder email(String value) {
            toBuild.email = value;
            return this;
        }

        public UsersResultBuilder iD(Integer value) {
            toBuild.iD = value;
            return this;
        }

        public UsersResultBuilder imie(String value) {
            toBuild.imie = value;
            return this;
        }

        public UsersResultBuilder login(String value) {
            toBuild.login = value;
            return this;
        }

        public UsersResultBuilder nazwisko(String value) {
            toBuild.nazwisko = value;
            return this;
        }

        public UsersResultBuilder password(String value) {
            toBuild.password = value;
            return this;
        }
    }
}
