/**
 * File generated by Magnet rest2mobile 1.1 - Jun 3, 2016 5:38:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.compscitutorials.basigarcia.navigationdrawervideotutorial.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;


public interface FactoryAPI {

  /**
   * Generated from URL GET https://polar-plains-14145.herokuapp.com/allocations
   * GET allocations
   * @param listener
   * @return void
   */
  Call<Void> get_Parking_Reservation(StateChangedListener listener);
}
