/**
 * File generated by Magnet rest2mobile 1.1 - May 28, 2016 12:00:19 AM
 * @see {@link http://developer.magnet.com}
 */

package com.compscitutorials.basigarcia.navigationdrawervideotutorial.TEMP;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.compscitutorials.basigarcia.navigationdrawervideotutorial.model.beans.*;
import java.util.List;

public interface FactoryAPI {

  /**
   * Generated from URL GET https://polar-plains-14145.herokuapp.com/users
   * GET users
   * @param listener
   * @return List<UsersResult>
   */
  Call<List<UsersResult>> getUsers(StateChangedListener listener);

  /**
   * Generated from URL GET http://polar-plains-14145.herokuapp.com/parks
   * GET parks
   * @param listener
   * @return List<_ParkingsResult>
   */
  Call<List<_ParkingsResult>> get_Parkings(StateChangedListener listener);

  /**
   * Generated from URL GET https://polar-plains-14145.herokuapp.com/allocations
   * GET allocations
   * @param listener
   * @return List<Parking_reservations1Result>
   */
 // Call<List<Parking_reservations1Result>> parking_reservations1(StateChangedListener listener);
}
